name: Check URL

on:
  schedule:
    # 定时运行任务（示例：每天检查一次）
    - cron: "0 * * * *"
  workflow_dispatch:
    # 手动触发运行
    inputs: {}

jobs:
  check_url:
    runs-on: ubuntu-latest

    steps:
    - name: Check website availability
      env:
        TARGET_URL: ${{ vars.TARGET_URL }}
      run: |
        echo "Checking URL: $TARGET_URL"
        HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" $TARGET_URL)
        if [ $HTTP_STATUS -eq 200 ]; then
          echo "✅ The URL is reachable with HTTP status $HTTP_STATUS."
        else
          echo "❌ The URL is not reachable. HTTP status: $HTTP_STATUS."
          exit 1
        fi
