name: test

on:
  push:
    branches: [ python-shell ]

jobs:
  test-job:
    name: 测试任务
    runs-on: ubuntu-latest

    steps:
      - name: action-test
        uses: shuxuecode/github-action@python-shell

      - name: push dist file to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with: 
          target_branch: output
          build_dir: /dist