name: test

on:
  push:
    branches: [ python-shell ]

jobs:
  test-job:
    name: 测试任务
    runs-on: ubuntu-latest

    steps:
      - name: action-test
        uses: shuxuecode/github-action@python-shell